# Environmental Variables
env:
    - COMPILE_LANG=python
    - COMPILE_LANG=arduino

sudo: required
language: $COMPILE_LANG
python:
    - "3.6"

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
    directories:
        - "~/.platformio"

# Pre-Install commands
install:
  - sudo pip install -U pip
  - if [ "${COMPILE_LANG}" = "python" ]; then pip install --user -U -r python/refs/requirements.txt; fi
  - if [ "${COMPILE_LANG}" = "arduino" ]; then pip install --user -U platformio; fi

# Script to build
script:
    - bash "scripts/build_${COMPILE_LANG}.sh"
